/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptsSlugRouteImport } from './routes/prompts.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsSlugRoute = PromptsSlugRouteImport.update({
  id: '/prompts/$slug',
  path: '/prompts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/prompts/$slug': typeof PromptsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/categories/$slug' | '/prompts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/categories/$slug' | '/prompts/$slug'
  id: '__root__' | '/' | '/categories/$slug' | '/prompts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  PromptsSlugRoute: typeof PromptsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$slug': {
      id: '/prompts/$slug'
      path: '/prompts/$slug'
      fullPath: '/prompts/$slug'
      preLoaderRoute: typeof PromptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  PromptsSlugRoute: PromptsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
